### ISSUE TITLE
Allow to specify tmp path

### ISSUE THREAD

**Issue by SolidTux** [jonhoo/openssh-rs#17]
It's probably not always a good idea to leave a temporary file in the working directory. Is there a reason why this is not in the tmp folder by default (std::env::temp_dir for example)?

**Comment by jonhoo** [comment]
The temporary file _should_ be automatically deleted when the connection is terminated. I had it be created in the current directory to make it easier to debug remote sessions by manually sshing in with the same key. I'd be totally open to making this behavior configurable through the builder though!

**Comment by jonhoo** [comment]
Fixed by #16
