### ISSUE TITLE
Port forwarding?

### ISSUE THREAD

**Issue by rakshith-ravi** [jonhoo/openssh-rs#22]
Is it possible to setup port forwarding along with this crate? I see in your source code that you're just calling the ssh command, which is perfect because then we can just add a `-R 80:localhost:80` or a `-L 80:localhost:80` to the ssh command based on what ports needs to be forwarded.

Would you be open to implementing that? Additionally, just out of curiosity, I see in other issues that you've not found time to work on this recently. As of today, does the library still work or are there any pitfalls in the library that prevent it from working for a production use?

**Comment by jonhoo** [comment]
It should be totally possible to add — want to give writing a PR a try? I'd be happy to review!

As far as I'm aware, this library still works well, and doesn't have any known pitfalls :) It's only a wrapper around `ssh` after all, so it's sort of limited how badly wrong it can be!

**Comment by rakshith-ravi** [comment]
Haha okay. Sounds good. I'd be happy to try and implement this in a PR. Where would I start with? What should I look into to get an understanding of the code?

**Comment by jonhoo** [comment]
Nice! I would start out looking at how Sftp is implemented, starting here:
https://github.com/jonhoo/openssh-rs/blob/bdb9e34cad2438ba5e243999c80b0fa0973d9e83/src/lib.rs#L311

and extending into https://github.com/jonhoo/openssh-rs/blob/master/src/sftp.rs. Port forwarding _should_ be even easier than that. I'm thinking something like a method on `Session` that returns a `struct OpenPort`, where dropping that then closes the port again.

**Comment by rakshith-ravi** [comment]
So I'm a little confused. How does this work with sftp with the same session? Doesn't sftp require you to run a separate command altogether than ssh? How does this open an ssh connection and subsequently open an sftp connection on the same ssh connection? I'm wondering because port forwarding requires you to run a bunch of args while calling the ssh command, and I'm wondering how I can do that _after_ I've opened a connection. Maybe I don't know enough about ssh, but I'm confused how it's structured. Any help would be appreciated.

**Comment by jonhoo** [comment]
Ah! We're pulling a little trick using SSH's support for multiplexing. Basically, we run one ssh command that is the _main_ connection to the server, and then we tell subsequent invocations of the ssh command to re-use that same connection, and just open another "channel" on top of it. You can read a bunch more details at https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing. Most of the details are hidden from you by the internals of the library — you basically just have to invoke the `ssh` command, and the library will take care that it re-uses the existing connection behind the scenes.

**Comment by rakshith-ravi** [comment]
Oh nice! That sounds fancy. So I just need to take care of opening an ssh connection, with the required parameters, yeah? Sounds simple enough. I'll try coming up with a PR. Thanks!

**Comment by NobodyXu** [comment]
@rakshith-ravi #26 adds port forwarding functionality and integration test for it.
