### ISSUE TITLE
[Proposal] Connect to ssh multiplex server directly with NobodyXu/openssh-mux-client

### ISSUE THREAD

**Issue by NobodyXu** [jonhoo/openssh-rs#25]
Hi

First of all, this crate is really awesome in that it can reuse all the ssh configuration `~/.ssh/config` and features it have.
Thank you for implementing this!

After I realized that this crate communicates with the ssh multiplex server by creating a `ssh` process and thus having problem handle errors reliably, I have been thinking of writing a Rust crate that can communicate with the ssh multiplex server directly.

Fortunately, ssh does have a [document] on its multiplex protocol and I was able to implement [openssh-mux-client](https://github.com/NobodyXu/openssh-mux-client) that acts as a ssh multiplex client in pure Rust.

I have written a few test cases to make sure the
 - health check
 - session opening
 - remote port forwarding
 - local port forwarding
 - graceful shutdown of the ssh multiplex server

are working as intended, while features
 - ~~local port forwarding~~
 - dynamic forwarding
 - ~~terminating the ssh multiplex server~~

are implemented but not tested.

There are also two features that I didn't implement:
 - forward stdio (stdin + stdout) to remote port (not that useful)
 - closure of port forwarding (according to the [document], it is not implemented yet by ssh)
 - terminating the ssh multiplex server for the ssh implementation is buggy (the server does not reply with the Ok message before it terminates).

While it is extremely likely there are bugs in my code, I think it is ready for testing.
Thus, I think it would be great if `openssh-rs` could add a feature that enables it to use my crate to communicate with the ssh multiplex server directly, which would help provides better error message and would avoid the unnecessary process creation.

[document]: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.mux

**Comment by jonhoo** [comment]
That's really neat! I'd definitely be interested in a CR that tried to integrate it behind a feature flag + configuration option. I am hesitant to add a GPL-licensed dependency though, so at the very least it would be off-by-default.

**Comment by NobodyXu** [comment]
I think I can switch to MIT/Apache license, since nobody other than me have contributed any code to this project.

**Comment by NobodyXu** [comment]
@jonhoo I've switched the license of my project to MIT now.

**Comment by NobodyXu** [comment]
[openssh-mux-client]'s dependencies all uses MIT/Apache/BSD, including [ssh_mux_format](https://github.com/NobodyXu/ssh_mux_format).

So the license issue shouldn't be a shower stopper now.

[openssh-mux-client]: https://github.com/NobodyXu/openssh-mux-client

**Comment by NobodyXu** [comment]
BTW, I just updated the crate and add test for graceful shutdown.

Now, it is possible to for openssh-rs to do session opening and server shutdown without spawning any process.

**Comment by NobodyXu** [comment]
@jonhoo Here's a preview PR that contains the alternative implementation using openssh-mux-client.
