### ISSUE TITLE
Connection failure depending on the current working directory

### ISSUE THREAD

**Issue by mrzv** [jonhoo/openssh-rs#27]
I have a code that calls `Session::connect(...).await`. It runs fine most of the time, but fails with "failed to connect to the remote host", when run from inside a certain directory (or its children). (I.e., the only thing that changes is the current working directory.) I don't see anything special about that directory, but perhaps I'm missing something. Any pointers on what this could be, or how to go about debugging it?

**Comment by NobodyXu** [comment]
@mrzv Can you use `Debug` trait to print the error so that the wrapped `io::Error` is also printed?

**Comment by NobodyXu** [comment]
According to [`man unix(7)`](https://man7.org/linux/man-pages/man7/unix.7.html):

> struct sockaddr_un {
>     sa_family_t sun_family;               /* AF_UNIX */
>     char        sun_path[108];            /* Pathname */
> };

>        *  The length of the pathname, including the terminating null byte, should not exceed the size of sun_path.

The maximum length of the pathname is `107` bytes and it seems like `ssh` is trying to pass absolute path to `bind`.

So maybe just `SessionBuilder::control_directory` to `/tmp`?
That would ensure the program can run without any error.
