### ISSUE TITLE
Session within a Session

### ISSUE THREAD

**Issue by omid** [jonhoo/openssh-rs#29]
Is it possible to have a `Session` within another `Session`?

**Comment by NobodyXu** [comment]
I am afraid that this is impossible.

`Session` is basically a RAII wrapper for ssh multiplex master.
They are independent of each other.

Can you please provide more information on what you are trying to archive here?

**Comment by omid** [comment]
I would like to connect from local to server1 and from there to server2 and then run commands.

local > server1 > server2

**Comment by NobodyXu** [comment]
Are you using server1 as a proxy?

Currently, `SessionBuilder` doesn't have the option to set proxy, but it should be trivial to add one given that we simply pass that to `ssh` multiplex master

**Comment by omid** [comment]
> Are you using server1 as a proxy?

yes

**Comment by NobodyXu** [comment]
I just realized there is one way to do this in the current version of `openssh` by using [`SessionBuilder::config_file`](https://docs.rs/openssh/latest/openssh/struct.SessionBuilder.html#method.config_file), which enables you to set an alternative config file.

You can then provide a config file where `ProxyJump` is set to the proxy "sever1".

ssh would handle the rest.

**Comment by NobodyXu** [comment]
Or you can do something like this:

Create a [`Session`](https://docs.rs/openssh/latest/openssh/struct.Session.html) to server1, then launch another `ssh` on server1.

Though this method cannot handle error in creating connection to server2 in server 1 well.

**Comment by NobodyXu** [comment]
Another method that works in #26 :

Connect to server1, then launch the ssh multiplex master on it.
Then use port forwarding to forward the control socket for the master into the local machine, and use [`openssh-mux-client`](https://github.com/NobodyXu/openssh-mux-client/) directly to connect to server2.

**Comment by omid** [comment]
Thanks a lot @NobodyXu

**Comment by NobodyXu** [comment]
You are welcome.
