### ISSUE TITLE
Streaming stdout with stderr together

### ISSUE THREAD

**Issue by jaywonchung** [jonhoo/openssh-rs#32]
Hi! Thanks as always for the great crates (and videos).

I'm writing a multi-node command runner built around this crate (https://github.com/jaywonchung/pegasus), and I have the need to stream both the stdout and stderr of commands to the user.

My take on streaming the stdout is like this:
https://github.com/jaywonchung/pegasus/blob/a92f27a48d7a768f5d6d9cc4e304a7c917010749/src/session.rs#L49-L77
(Basically I'm using `AsyncBufReadExt::fill_buf` to fetch characters.)

Now, building on top of this, I'd like to stream stdout together with stderr. I thought in theory stdout and stderr are separate, it should be safe to create a replica `async fn stream_stderr(&self, stdout: &mut ChildStderr)` and join them like:

```rust
futures::future::join(
    stream_stdout(process.stdout().as_mut().unwrap()),
    stream_stderr(process.stderr().as_mut().unwrap()),
).await
```

but obviously this erred with the borrow checker complaining about `process` being mutably borrowed twice.

Approaches that failed:

1. `process.channel.take()`: Failed because the field `channel` is private.
2. `let openssh::RemoteChild { session, channel } = process`: Failed because `tokio::process::Child` doesn't (cannot?) implement `Copy`.

Would there be a way to get around this?

Thanks.

**Comment by NobodyXu** [comment]
You almost got it right:

    process.stdout().take().unwrap()

that will return "ChildStdout" by value, instead of a mutable reference.

Similarly, you can also obtain a "ChildStderr" in the same way.

**Comment by NobodyXu** [comment]
You can join these two streaming using the following code:

```
let mut stdout = process.stdout().take().unwrap();
let mut stderr = process.stderr().take().unwrap();

futures::future::join(
    stream_stdout(stdout),
    stream_stderr(stderr),
).await
```

**Comment by jaywonchung** [comment]
Wow, thanks @NobodyXu! That did the job perfectly!!

I also made it generic `async fn stream<R: AsyncRead + Unpin>(&self, stream: R)` and it seems to work greatly.
